### ISSUE TITLE
reuseport.go:47:7: undefined: reuseport.Dialer

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-reuseport-transport#5]
```
# github.com/libp2p/go-reuseport-transport
../../libp2p/go-reuseport-transport/reuseport.go:47:7: undefined: reuseport.Dialer
```

Broken by https://github.com/libp2p/go-reuseport/pull/56

**Comment by anacrolix** [comment]
See #6.

**Comment by Stebalien** [comment]
Fixed.
